### ISSUE TITLE
Created config per readme but does not send to syslog server

### ISSUE THREAD

**Issue by iamleet** [dlackty/fluent-plugin-remote_syslog#21]
Greetings, I have the following config but, I am not able to see any incoming packets to 514 on the server when I run tcpdump. Any info would be great.  

```
<source>
  type forward
  port 24224
  bind 0.0.0.0
</source>

<match *.*>
  type copy
  <store>
    type file
    path /var/log/fluent/myapp
    time_slice_format %Y%m%d
    time_slice_wait 10m
    time_format %Y%m%dT%H%M%S
    compress gzip
    utc
  </store>
  <store>
    type remote_syslog
    host XX.XX.XX.XX
    port 514
    tag fluentd
  </store>

</match>
```

**Comment by fragatina** [comment]
Hamlet,

try adding "severity debug" to the remote_syslog config

**Comment by iamleet** [comment]
@fragatina I am going to close this issue because I won't be able to recreate it. Had to go with a syslog container for collecting the logs from all the containers running on the host. I didn't need to change anything on the aggregator to get this to work correctly. Can't help but feel the issue was in the fluentd container's configuration at this point. Thanks for the response.  -noobsauce
