### ISSUE TITLE
Possible to pass through the hostname and the tag fields to the remote syslog?

### ISSUE THREAD

**Issue by samitpal** [dlackty/fluent-plugin-remote_syslog#29]
I have an architecture where I get parsed fields to fluentd. I then have a requirement to send these events to a remote syslog in addition to sending to ES. I tested with your plugin and it works well except that I was interested in sending the original hostname and the tag (program) to the remote syslog. Is that possible?

**Comment by samitpal** [comment]
Ok, playing a bit more with the configs, it seems all I had to do is set place holders for program and hostname.
      

> program ${ident}
> hostname ${host}
> 
> <buffer ident,host>
> </buffer>

**Comment by samitpal** [comment]
I'm closing the issue.

**Comment by scalp42** [comment]
@samitpal can you share your config?
