### ISSUE TITLE
Removing the metadata sent with each log.

### ISSUE THREAD

**Issue by achin-netskope** [dlackty/fluent-plugin-remote_syslog#36]
Hi,
I get some meta data sent with each log for example. 
**<13>Aug 22 10:53:42 devbox fluentd:** {"message":"Some log message"}
Here _<13>Aug 22 10:53:42 devbox fluentd:_ is redundant for me. How can I remove this from the transmitted log ?
Best.

**Comment by achin-netskope** [comment]
Found a work around.
Closing now.

**Comment by achilles-git** [comment]
@achin-netskope did you find a way to get rid of those metadata ?
